### ISSUE TITLE
Learn pythonic concepts

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-OlenaEfymenko#11]
* [x] [PEP 8] (common conventions of writing and organizing code in the pythonic world)
  * [x] https://realpython.com/python-pep8/
* [x] [PEP 20] (Zen Of Python)
```python
import this
```
* [x] [PEP 257] (common conventions of writing docstrings)
* [x] linters: flake8, pylint
* [x] virtualenv
  * [x] pyenv (install one locally using pyenv-installer, enable pyenv-virtualenv as well) -> #10
* [x] zsh (install and enable this shell in your machine)
  * [x] install oh-my-zsh framework to configure nice and useful terminal environment -> #9
* [x] Bookmark https://gist.github.com/webknjaz/b623cb5eb941ed17617afa831f4a7fb0 for things to learn in the future

[PEP 8]: https://pep8.org
[PEP 20]: https://zen-of-python.info/
[PEP 257]: https://www.python.org/dev/peps/pep-0257/

**Comment by OlenaYefymenko** [comment]
Sviatoslave, hello.
I have also decided to add more practice -  writing in Python + theory. I would try VS Code, if I need to test some script quickly. Because, for Vim, I considered need more time for experience. In VS Code I faced problem by executing `Run Code `in the workspace, after modifying script, output don't update. Only after `Run Python File`, output changes.
From user (without creating workspace) modifying in scripts are displayed correct after command `Run Code.` I searched in Google this answer, but have doubts:

> **Run Code** is provided by the extension [Code Runner](https://github.com/formulahendry/vscode-code-runner), which will only show the result in OUTPUT and not accept input.
> 
> While **Run Python File in Terminal** is provided by [Python](https://github.com/Microsoft/vscode-python) extension, it will open a terminal panel in which your Python interpreter is automatically activated, then runs `python3``[hello.py](https://hello.py/)`(macOS/Linux) or `python``[hello.py](https://hello.py/)`(Windows). It both displays outputs and accepts input.

What do you think could be the problem? The cause may be in the path that needs to be updated in Settings?

And a general question, that is now more often used in companies (IDE, text editors)? Should I switch completely to Vim?

**Comment by webknjaz** [comment]
I almost don't use VS Code myself and never use it to run Python programs. I always use the terminal where I understand the environment state because it's fully under my control. I know which env is activated and sometimes use the full path to the desired interpreter if needed. So if you use VS Code for editing, you can try using its terminal to run stuff or run the scripts through a separate Kitty session. It's up to you. You can also dig deeper into setting up a more integrated experience with VS Code, this is not something I looked into much.

Some companies or rather teams may be using certain code editors or IDEs in which case, many people are able to help each other because the environment is mostly similar/identical.

Most of the time, it is allowed to use anything you're comfortable with.
Choosing Vim is a deeply personal choice made consciously. You may use it or not but it is is useful to be generally familiar with it. You may end up having to use it on remote systems where it's often available by default while you won't be able to keep using graphical tools there. This is the source of its importance.

You can keep it as a tool for writing commit messages when using Git (setting `EDITOR=nvim` should do) from the terminal and that's enough to keep the basic usage skills sharp. This is just an aspect of letting yourself feel comfortable working with the terminal.
