### ISSUE TITLE
Switch to zsh and configure oh-my-zsh

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-OlenaEfymenko#9]
* Employ your googling skills to figure out how to change the default *NIX user shell
* Read up on the user-level zsh configuration
* https://ohmyz.sh is a good start, play with changing the configs, figure out where to put own configuration via own plugins, and where to put non-default themes; enable some of the built-in plugins that are related to Python, Git and other tooling you might be using often
  * some plugins, like `fzf`, require additional software to be installed, besides omz itself
* Integrate https://github.com/spaceship-prompt/spaceship-prompt/ — a popular theme that is ideal for dev envs;  it's README has instruction for integration with omz; also the author is responsive and helpful

**Comment by OlenaYefymenko** [comment]
Hello, Sviatoslav
I changed shell (bash to zsh). Also installed omz

- played with different themes in `~/.zshrc`
- installed powerline-fonts
- analyzed `~/.zsh_history` (it looks very pretty with different colors)
- tested Autosuggestion, but turned it off for now (need more practice with typing independently)
- installed pew 
- finally, chose` ZSH_THEME="spaceship"`
- `fzf`
In `~/.zshrc` (in the plugin settings) pro tempore:
```
plugins=(
zsh-syntax-highlighting
git
fzf
)
```
I will add others by learning likely :)

**Comment by OlenaYefymenko** [comment]
@webknjaz 

> Not sure if that's needed, but FWIW if there are any symbols necessary to be rendered in a different font, you can specify a symbol map in Kitty config, but you'd need to know the unicode char codes for those.

I made a mistake by writing the status of this issue, sorry, I just downloaded it, not installed it, because seen a lot of recommendations about this font by reading the manual for switching to zsh. I still use Nerd Font. As a symbol map in Kitty, I understood.

> > It's best to have it on, really. You can still type things if you want, but better learn to make use of autocompletions. Especially, using the Tab key all the time — this also helps make less typos which is sometimes crucial.

I was in a hurry to draw conclusions. It is really more comfortable and faster. 

> In one of the following tasks, you'll be asked to install pyenv which has its own way of managing virtualenvs. Make sure they don't conflict with each other.

For now, I removed it and moved on to the next issue#10 for experience.

> Try also common-aliases, docker, last-working-dir, pep8, pip, pyenv, pylint, python, sudo, systemd.

Also were added and set editor.

I have only one clarification, I edited syntax in` ~/.zshrc`. And If I made a syntax error, the next time I opened the terminal I would get an error message? I ask because there are always doubts when I edit the configuration settings. Everything is working fine now, I am asking about the future

**Comment by OlenaYefymenko** [comment]
Ок, thank you! I am going to practice your recommendations.
